// Builds oxc (parser + transformer) from source to wasm32-wasip1-threads and embeds it (deflate-raw + base93) into src/_vendor/wasm.ts (committed)
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import { inflateRawSync } from "node:zlib";

const require = createRequire(import.meta.url);
const pkgVersion = (name: string): string => require(`${name}/package.json`).version;

const oxcVersion = pkgVersion("oxc-transform");
const parserVersion = pkgVersion("oxc-parser");
if (oxcVersion !== parserVersion) {
  throw new Error(`Version mismatch: oxc-transform@${oxcVersion} vs oxc-parser@${parserVersion}`);
}

const root = fileURLToPath(new URL("..", import.meta.url));
const oxcDir = `${root}vendor/oxc`;
const tag = `crates_v${oxcVersion}`;
const run = (cmd: string, args: string[], cwd = root) =>
  execFileSync(cmd, args, { cwd, stdio: "inherit" });

if (!existsSync(oxcDir)) {
  run("git", [
    "clone",
    "--depth=1",
    `--branch=${tag}`,
    "https://github.com/oxc-project/oxc.git",
    oxcDir,
  ]);
} else if (execFileSync("git", ["describe", "--tags"], { cwd: oxcDir }).toString().trim() !== tag) {
  run("git", ["fetch", "--depth=1", "origin", "tag", tag], oxcDir);
  run("git", ["checkout", tag], oxcDir);
}

// Strip machine-specific paths (panic locations) so the committed wasm is reproducible
const cargoHome = process.env.CARGO_HOME || `${homedir()}/.cargo`;
// `--config` arrays merge with `rust/.cargo/config.toml` (`RUSTFLAGS` would replace its rustflags)
const rustflags = [
  `--remap-path-prefix=${root}=`,
  `--remap-path-prefix=${cargoHome}/registry/src/=`,
];
run(
  "cargo",
  ["build", "--release", "--config", `build.rustflags=${JSON.stringify(rustflags)}`],
  `${root}rust`,
);

const wasm = readFileSync(`${root}rust/target/wasm32-wasip1-threads/release/oxbox.wasm`);
// deflate-raw: natively decompressible everywhere (node:zlib, DecompressionStream); zopfli is ~5% smaller than zlib -9
const deflated = execFileSync("cargo", ["run", "--release", "--quiet", "--", "5"], {
  cwd: `${root}scripts/zopfli`,
  input: wasm,
  stdio: ["pipe", "pipe", "inherit"],
  maxBuffer: 1 << 30,
  env: { ...process.env, CARGO_TARGET_DIR: `${root}rust/target` },
});
if (!inflateRawSync(deflated).equals(wasm)) throw new Error("zopfli roundtrip mismatch");

// base93: 13 bits per 2 chars, alphabet is printable ASCII except `"` and `\` (safe in a "..." literal)
const alphabet = Array.from({ length: 95 }, (_, i) => String.fromCodePoint(i + 32)).filter(
  (c) => c !== '"' && c !== "\\",
);
const chars: string[] = [];
const push = (v: number) => chars.push(alphabet[v % 93]!, alphabet[Math.floor(v / 93)]!);
let buf = 0;
let bits = 0;
for (const byte of deflated) {
  buf |= byte << bits;
  bits += 8;
  if (bits >= 13) {
    push(buf & 8191);
    buf >>>= 13;
    bits -= 13;
  }
}
if (bits) push(buf);
const data = chars.join("");

const outDir = new URL("../src/_vendor/", import.meta.url);
mkdirSync(outDir, { recursive: true });
writeFileSync(
  new URL("wasm.ts", outDir),
  `// Generated by scripts/vendor.ts (do not edit): oxc@${oxcVersion} wasm, deflate-raw (zopfli) + base93
import { getBuiltin } from "../napi.ts";

export const oxcVersion = ${JSON.stringify(oxcVersion)};

/** Decompresses the embedded wasm binary synchronously (Node.js). */
export const wasm = (): Uint8Array => getBuiltin("node:zlib").inflateRawSync(deflated());

/** Decompresses the embedded wasm binary with the web \`DecompressionStream\`. */
export const wasmAsync = async (): Promise<Uint8Array> =>
  new Uint8Array(
    await new Response(
      new Blob([deflated()]).stream().pipeThrough(new DecompressionStream("deflate-raw")),
    ).arrayBuffer(),
  );

function deflated(): Uint8Array<ArrayBuffer> {
  const out = new Uint8Array(${deflated.length});
  const at = (i: number) => {
    const c = data.charCodeAt(i);
    return c - 32 - +(c > 34) - +(c > 92);
  };
  for (let i = 0, o = 0, buf = 0, bits = 0; o < out.length; i += 2) {
    buf |= (at(i) + at(i + 1) * 93) << bits;
    for (bits += 13; bits >= 8 && o < out.length; bits -= 8, buf >>>= 8) out[o++] = buf;
  }
  return out;
}

const data =
  "${data}";
`,
);

const kb = (n: number) => `${(n / 1024).toFixed(0)} KB`;
console.log(
  `Built oxc@${oxcVersion}: ${kb(wasm.length)} wasm -> ${kb(deflated.length)} deflate -> ${kb(data.length)} base93`,
);
